version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00" # 13:00(UTC+9)
      day: monday
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00" # 13:00(UTC+9)
      day: monday
