[build]
  publish = "dist"
  command = "npm run build"

[context.deploy-preview.environment]
  GIT_LFS_ENABLED ="true"
  NODE_VERSION = "22"

[context.production.environment]
  GIT_LFS_ENABLED ="true"
  NODE_VERSION = "22"
