name: Add this week's blog PR
on:
  workflow_dispatch:
  schedule:
  - cron: 0 3 * * 1

jobs:
  add-this-week-template:
    name: Add this week post's branch
    runs-on: ubuntu-latest
    steps:

    - name: Get GitHub App Token
      uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create Post Directory
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TZ: 'Asia/Tokyo'
      run: .github/workflows/add-blog-post.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: create-pull-request
      with:
        branch: ${{ env.slug }}
        commit-message: "[skip ci] initialize ${{ env.slug }} blog post"
        token: ${{ steps.generate-token.outputs.token }}
        sign-commits: true
        title: "[post] ${{ env.slug }}"
        body: |
          - **target:** ${{ env.from_date }}(Mon) ~ ${{ env.to_date }}(Sun)

          ## this week's theme

          - what's up?

          ## FYI

          - :blue_heart: [Tweet Log - Twitter](https://twitter.com/search?q=(from%3Alegnoh)%20until%3A${{ env.to_date }}%20since%3A${{ env.from_date }}%20-filter%3Areplies&src=typed_query)
          - :computer: [Commit Log - GitHub](https://github.com/legnoh?tab=overview&from=${{ env.from_date }}&to=${{ env.to_date }})
          - :train: [Timeline - Google Maps](https://www.google.com/maps/timeline?pb=!1m2!1m1!1s${{ env.from_date }})
          - :shopping_cart: Order history: [Yahoo! Shopping](https://odhistory.shopping.yahoo.co.jp/order-history/list) | [Amazon](https://www.amazon.co.jp/gp/css/order-history)
          - :money_with_wings: [Expenses - MoneyForward](https://moneyforward.com/cf)
          - :bookmark_tabs: [My Bookmark - Hatena Bookmark](https://b.hatena.ne.jp/Ryo_K/bookmark)
          - :drop_of_blood: [Timeline - Withings Health Mate](https://healthmate.withings.com/timeline)
          - :sun_with_face: [Weather forecast - OpenWeatherMap](https://openweathermap.org/city/1850144)
        labels: posts
        assignees: legnoh
