name: CI

on:
  pull_request_target:
    branches: ["main"]
  workflow_dispatch:

jobs:
    build:
        runs-on: macos-14 # pagefind not working on x64 architecture
        steps:
        - uses: actions/checkout@v4
          with:
            lfs: true
        - uses: actions/setup-node@v4
          with:
            node-version: 18
            cache: 'npm'
        - name: Run npm ci
          run: npm install --include=dev
        - name: Run astro check
          run: npm run check
        - name: Run astro build
          run: npm run build
        - name: Deploy to Netlify
          uses: nwtgck/actions-netlify@v3.0
          with:
            publish-dir: './dist'
            production-deploy: false
            github-token: ${{ secrets.GITHUB_TOKEN }}
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
