name: Cleanup Codespaces
on:
  workflow_dispatch:
  schedule:
  - cron: 0 3 * * 2

jobs:
  nightly:
    name: delete empty codespaces
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Empty Codespace
        uses: NickLiffen/delete-empty-codespaces@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.CODESPACE_TOKEN }}
